export default [
  "Follow Discord's Terms of Service and Guidelines",
  'No Doxxing / Sexual Harassment',
  'Try not to spam messages and/or (role) pings',
  'You are not allowed to promote other servers in any of the channels without permission',
  'NSFW content is only allowed in the NSFW channels',
  'Do not impersonate others',
  'Do not upload harmful links or media (NSFL or links to things such as malware)',
  'Only speak/text in English, failure to do so will lead to a warn/kick/ban',
  'Do not post loli/shota/cub or feral/bestiality content',
  'Please use only normal characters for your Discord (nick)name',
  'All staff members are allowed to kick/ban/mute you even if you have not broken a rule',
  'No people under 16',
  'Post only channel related content, move regular conversation to the general-talk chat',
]
