name: check-buildability
on: [push, pull_request]
jobs:
  install-dependencies:
    name: Install Dependencies
    runs-on: ubuntu-latest
    steps:
      - run: echo Installing Dependencies
      - run: npm install
  check-build:
    needs: install-dependencies
    runs-on: ubuntu-latest
    steps:
      - run: echo Checking Buildability
      - run: npm run build
